#  女性倾向跨性别者的激素治疗简介

| 作者 [Aly W.][1] | 首次出版于 二零一八年八月四日 | 最后修改于 二零二一年六月二十二日 |
| --- | --- | --- |

   [1]: https://transfemscience.org/about/#aly-w

| 译者 yucandy | 翻译于 二零二一年六月二十三日 |
| --- | --- |

##  前言

###  提要 / 一句话简介

性激素，如雌激素、睾酮和孕酮，由性腺产生。性激素影响第二性征的发展。睾酮导致男性化，而雌二醇导致女性化和乳房发育。男性有大量的睾酮，而女性有低量的睾酮和大量的雌二醇。这些激素差异造成了男女间身体上的不同。女性倾向跨性别者使用性激素和其他激素类药物，将激素状况从男性典型转变成女性典型。这导致了女性化，并能够缓解性别焦虑。女性化激素治疗引起的变化发生在几个月到几年的时间里。有许多不同类型的激素药物，其可以通过不同的途径进行给药。例如，口服的丸/片剂，外用的贴片和凝胶，及注射剂等。不同的激素药物、途径和剂量有不同的疗效、副作用和风险。激素治疗应定期通过血液检查进行监测，以确保疗效和安全，并在需要时调整。

##  性激素

###  种类和效果

[性激素][2] 包括 [雌激素][3] (E)，[孕激素][4] (P)，和 [雄激素][5]。一个人的激素状况 (hormonal profile) 是其天生的 [性腺][6] 的产物。出生时男性有 [睾丸][7] 而女性有 [卵巢][8]。睾丸产生大量的雄激素和少量的雌激素，而卵巢则产生大量的雌激素、孕酮与少量的雄激素。

   [2]: http://en.wikipedia.org/wiki/Sex_steroid
   [3]: https://en.wikipedia.org/wiki/Estrogen
   [4]: https://en.wikipedia.org/wiki/Progestogen
   [5]: https://en.wikipedia.org/wiki/Androgen
   [6]: http://en.wikipedia.org/wiki/Gonad
   [7]: http://en.wikipedia.org/wiki/Testicle
   [8]: https://en.wikipedia.org/wiki/Ovary

体内的主要雌激素是 [雌二醇][9] (E2)，主要孕激素是 [孕酮][10] (P4)，主要雄激素是 [睾酮][11] (T) 和 [双氢睾酮][12] (DHT)。性激素导致并决定 [第二性征][13]。它们通过作为细胞内的 [激动剂][14] （激活剂）来影响 [受体][15] 作用。这些受体包括 [雄激素受体][16] (AR)，[雌激素受体][17] (ER)，和 [孕激素受体][18] (PR)。激活后，这些受体调节 [基因表达][19] 以影响细胞和 [组织][20]。

   [9]: https://en.wikipedia.org/wiki/Estradiol
   [10]: https://en.wikipedia.org/wiki/Progesterone
   [11]: https://en.wikipedia.org/wiki/Testosterone
   [12]: https://en.wikipedia.org/wiki/Dihydrotestosterone
   [13]: https://en.wikipedia.org/wiki/Secondary_sex_characteristic
   [14]: https://en.wikipedia.org/wiki/Agonist
   [15]: https://en.wikipedia.org/wiki/Receptor_(biochemistry)
   [16]: https://en.wikipedia.org/wiki/Androgen_receptor
   [17]: https://en.wikipedia.org/wiki/Estrogen_receptor
   [18]: https://en.wikipedia.org/wiki/Progesterone_receptor
   [19]: https://en.wikipedia.org/wiki/Gene_expression
   [20]: http://en.wikipedia.org/wiki/Tissue_(biology)

雌激素导致女性化。这包括 [乳房发育][21]、皮肤软化、 [脂肪分布女性化][22] （集中于乳房、髋部、大腿与臀部）、 [臀部变宽][23] （在 [骺板][24] 尚未闭合的人中)），以及其他变化。 ([维基][25]) 

   [21]: https://en.wikipedia.org/wiki/Breast_development
   [22]: https://en.wikipedia.org/wiki/Gynoid_fat_distribution
   [23]: https://en.wikipedia.org/wiki/Hip#Sexual_dimorphism_and_cultural_significance
   [24]: https://en.wikipedia.org/wiki/Epiphyseal_plate
   [25]: https://en.wikipedia.org/wiki/Pharmacodynamics_of_estradiol#Effects_in_the_body_and_brain

孕激素在女性化或 [青春期][26] 乳房发育中基本上没有已知的作用。孕激素不作为女性化的媒介，但是却在 [女性生殖系统][27] 中具有重要的作用。其是 [怀孕][28] 期间必不可少的激素。 ([维基][29]) 孕激素也阻止雌激素在身体某些部位中的作用，如 [子宫][30]、阴道和乳房。([维基][31]) 

   [26]: http://en.wikipedia.org/wiki/Puberty
   [27]: https://en.wikipedia.org/wiki/Female_reproductive_system
   [28]: https://en.wikipedia.org/wiki/Pregnancy
   [29]: https://en.wikipedia.org/wiki/Pharmacodynamics_of_progesterone#Effects_in_the_body_and_brain
   [30]: https://en.wikipedia.org/wiki/Uterus
   [31]: https://en.wikipedia.org/wiki/Pharmacodynamics_of_progesterone#Antiestrogenic_effects

雄激素导致 [男性化][32]. 这包括 [阴茎的增长][33]，[肩膀的变宽][34]，[肋骨的扩张][35]，[肌肉的增长][36]，[声音的加深][37]，[脂肪分布的男性化模式][38] （集中在腹部和腰部），以及 [面部、身体毛发的生长][39] ([维基][40])。雄性激素还导致各种普遍不受欢迎的皮肤和头发影响，如 [油性皮肤][41]、[痤疮][42]、[皮脂溢出][43]、[头皮脱发][44] 和 [体味][45]。此外，雄激素还阻止由雌激素激发的乳房发育。

   [32]: https://en.wikipedia.org/wiki/Virilization
   [33]: https://en.wikipedia.org/wiki/Penile_growth
   [34]: https://en.wikipedia.org/wiki/Shoulder#Development
   [35]: https://en.wikipedia.org/wiki/Rib_cage#Development
   [36]: https://en.wikipedia.org/wiki/Muscle_growth
   [37]: https://en.wikipedia.org/wiki/Voice_change
   [38]: https://en.wikipedia.org/wiki/Android_fat_distribution
   [39]: http://en.wikipedia.org/wiki/Hair_growth
   [40]: https://en.wikipedia.org/wiki/Testosterone_(medication)#Effects_in_the_body_and_brain
   [41]: https://en.wikipedia.org/wiki/Oily_skin
   [42]: https://en.wikipedia.org/wiki/Acne
   [43]: https://en.wikipedia.org/wiki/Seborrhoeic_dermatitis
   [44]: https://en.wikipedia.org/wiki/Pattern_hair_loss
   [45]: https://en.wikipedia.org/wiki/Body_odor

除了对身体的影响外，性激素在大脑中也有作用。这些作用影响认知、情绪和行为。例如，雄激素在男性中产生明显的 [性欲][46] 和 [唤醒][47] （包括 [自发勃起][48]），而雌激素是负责女性性欲的主要激素 ([Cappelletti & Wallen, 2016][49])。性激素对健康也有重要影响，这可以是积极或消极的。例如，雌激素可以保持 [骨骼强度][50]，并可能防止 [心脏疾病][51]，但也会增加 [乳腺癌][52] 的风险 ([Aly W., 2020][53])。

   [46]: https://en.wikipedia.org/wiki/Sexual_desire
   [47]: https://en.wikipedia.org/wiki/Sexual_arousal
   [48]: https://en.wikipedia.org/wiki/Erection
   [49]: https://doi.org/10.1016/j.yhbeh.2015.11.003
   [50]: https://en.wikipedia.org/wiki/Bone_density
   [51]: https://en.wikipedia.org/wiki/Coronary_artery_disease
   [52]: https://en.wikipedia.org/wiki/Breast_cancer
   [53]: https://transfemscience.org/articles/breast-cancer/

雌激素、孕激素和雄激素也有 [抗促性腺激素][54] 的作用。意思是，它们抑制 [促性腺激素释放激素][55] (GnRH) 诱导的 [促性腺激素][56]、[黄体生成素][57] (LH) 和 [卵泡刺激素][58] (FSH) 从大脑垂体中的分泌。促性腺激素向性腺发出信号，使其制造性激素并提供生育所需的精子和卵细胞。因此，促性腺激素水平的降低将导致性腺性激素分泌的减少和生育能力的降低。如果促性腺激素水平被充分抑制，性腺将完全不再制造性激素，生育能力将停止。体内绝大部分的雌二醇、睾酮和孕酮是由性腺产生的。其余少量的这些激素大部分是由 [肾上腺][60] 产生的，其位于 [肾脏][61] 顶部。 

   [54]: https://en.wikipedia.org/wiki/Antigonadotropin
   [55]: https://en.wikipedia.org/wiki/Gonadotropin-releasing_hormone
   [56]: https://en.wikipedia.org/wiki/Gonadotropin
   [57]: https://en.wikipedia.org/wiki/Luteinizing_hormone
   [58]: https://en.wikipedia.org/wiki/Follicle-stimulating_hormone
   [59]: https://en.wikipedia.org/wiki/Pituitary_gland
   [60]: https://en.wikipedia.org/wiki/Adrenal_gland
   [61]: http://en.wikipedia.org/wiki/Kidney

###  正常激素水平 

尽管不同顺性别女性的激素水平可能变化很大，其变化是可以根据正常的 [月经周期][62] 而预测的。月经周期持续约28天，由以下部分组成：

   [62]: https://en.wikipedia.org/wiki/Menstrual_cycle

  1. [卵泡期][63]—周期的前半段或第1-14天
  2. [周期中期][64]—周期中间或第12-16天左右
  3. [黄体期][65]—周期的后半段或第14-28天

   [63]: https://en.wikipedia.org/wiki/Follicular_phase
   [64]: https://en.wikipedia.org/wiki/Menstrual_cycle#Cycles_and_phases
   [65]: https://en.wikipedia.org/wiki/Luteal_phase

月经周期中的激素水平如下图所示：

![][66]

   [66]: https://transfemscience.org/assets/images/transfem-intro-e2-p4-cycle.png

图示: 绝经前妇女整个月经周期的雌二醇和孕酮中位数水平 ([Stricker et al., 2006][67]; [Abbott, 2009][68])。水平虚线是周期的平均水平。其他地方提供的图表显示了个体之间的变化。 ([维基-图表][69]; [维基-图表][70]; [维基-图表][71])

   [67]: https://doi.org/10.1515/CCLM.2006.160
   [68]: https://web.archive.org/web/20200127014925/http://www.ilexmedical.com/files/PDF/Estradiol_ARC.pdf
   [69]: https://commons.wikimedia.org/wiki/File:Estradiol_levels_with_LC-MS-MS_during_the_normal_menstrual_cycle_in_women.png
   [70]: https://commons.wikimedia.org/wiki/File:Estradiol_levels_across_the_normal_menstrual_cycle_in_women.png
   [71]: https://commons.wikimedia.org/wiki/File:Progesterone_levels_across_the_normal_menstrual_cycle_in_women.png

从图中可以看出，在卵泡期，雌二醇水平相对较低，孕酮水平非常低；在周期中期，雌二醇水平短暂激增至非常高的水平并触发 [排卵][72] ，孕酮不变；在黄体期，雌二醇和孕酮水平都经历了一个颠簸，相对较高（尽管雌二醇没有周期中期高峰时那么高）。

   [72]: https://en.wikipedia.org/wiki/Ovulation

下表显示了女性和男性的雌二醇、孕酮和睾酮的循环水平和生产率，并可在它们之间进行比较。

表格：主要性激素的循环水平<sup>a</sup>和预计生产率的区间<sup>b</sup>：

| 激素 | 群体 | 时间 | 水平<sup>c</sup> | 生产率 |
| --- | --- | --- | --- | --- | 
| [雌二醇][73] | 女性<sup>d</sup> | 卵泡期 | 5–180 pg/mL | 30–170 μg/day<sup>e</sup> |
| | | 周期中期（排卵） | 45–750 pg/mL | 320–950 μg/day<sup>e</sup> |
| | | 黄体期 | 20–300 pg/mL | 250–300 μg/day<sup>e</sup> |
| | 男性 | – | 8–35 pg/mL | 20–60 μg/day |
| [孕酮][74] | 女性<sup>d</sup> | 卵泡期 | ≤0.3 ng/mL | 0.75–5 mg/day |
| | | 周期中期（排卵） | 0.1–1.5 ng/mL | ? (低) |
| | | 黄体期 | 3.5–38 ng/mL | 15–50 mg/day<sup>f</sup> |
| | 男性 | – | ≤0.5 ng/mL | 0.75–3 mg/day |
| [睾酮][75] | 女性<sup>d</sup> | 月经周期 | 5–55 ng/dL | 190–260 μg/day |
| | 男性 | – | 250–1100 ng/dL | 6.5 mg/day |

   [73]: http://en.wikipedia.org/wiki/Estradiol
   [74]: https://en.wikipedia.org/wiki/Progesterone
   [75]: http://en.wikipedia.org/wiki/Testosterone

<sup>a</sup> 激素水平的来源：[Zhang & Stanczyk, 2013][76]; [Nakamoto, 2016][77]; [Styne, 2016][78]; [LabCorp, 2020][79]. <sup>b</sup> 生产率的来源：[Aufrère & Benson, 1976][80]; [Powers et al., 1985][81]; [Lauritzen, 1988][82]; [Carr, 1993][83]; [O’Connell, 1995][84]; [Kuhl, 2003][85]; [Strauss & FitzGerald, 2019][86]. <sup>c</sup> 使用 [液相色谱-质谱法][87] (LC–MS) (state-of-the-art blood tests). <sup>d</sup> 在停经前的成人月经周期中 [premenopause][88] (年龄 ~18–50 岁). <sup>e</sup>  整个月经周期的平均生产率约为 200 μg/day 或 6 mg/month ([Rosenfield, Cooke, & Radovich, 2021][89]). <sup>f</sup> 平均大概 25 mg/day (Carr, 1993).

   [76]: https://doi.org/10.1002/9781118671276.ch45
   [77]: https://doi.org/10.1016/B978-0-323-18907-1.00154-2
   [78]: https://doi.org/10.1007/978-3-319-18371-8_16
   [79]: https://web.archive.org/web/20200330030510/https://www.esoterix.com/sites/default/files/L5167-0320-17.pdf
   [80]: https://doi.org/10.1002/jps.2600650602
   [81]: https://doi.org/10.1016/0002-9378(85)90569-1
   [82]: https://docs.google.com/document/d/1vlUvDVON8ZrB_NeFqyQDRn-lvYUtV74lCmfBRP2DxzI/view
   [83]: https://scholar.google.com/scholar?cluster=16829789208796034783
   [84]: https://doi.org/10.1002/j.1552-4604.1995.tb04143.x
   [85]: https://www.kup.at/journals/summary/3583.html
   [86]: https://doi.org/10.1016/B978-0-323-47912-7.00004-4
   [87]: https://en.wikipedia.org/wiki/Liquid_chromatography%E2%80%93mass_spectrometry
   [88]: https://en.wikipedia.org/wiki/Premenopause
   [89]: https://doi.org/10.1016/B978-0-323-62520-3.00016-6

女性的平均雌二醇水平约为 100 pg/mL，男性为 25 pg/mL，而女性的平均睾酮水平约为 30 ng/dL，男性为 600 ng/dL。根据这些数值，男性的睾丸激素水平平均比女性高约20倍。在接受 [性腺切除术][90]（睾丸移除）的男性中，睾酮水平与女性相似 (<50 ng/dL)。([Nishiyama, 2014][91]; [Itty & Getzenberg, 2020][92])在有[雄性激素过剩][93] 症状的女性中（面部/ 身体毛发过度生长），如 [多囊卵巢综合症][94] (PCOS) 患者，其睾酮的平均水平约为 60 ng/dL。([Steinberger et al., 1998][95]) 因此，即使是相对于正常女性水平略微升高的睾丸激素水平也可能产生不良的雄性激素效应。

   [90]: https://en.wikipedia.org/wiki/Gonadectomy
   [91]: https://doi.org/10.1016/j.urolonc.2013.03.007
   [92]: https://doi.org/10.4103/aja.aja_139_19
   [93]: https://en.wikipedia.org/wiki/Hyperandrogenism
   [94]: https://en.wikipedia.org/wiki/Polycystic_ovary_syndrome
   [95]: https://doi.org/10.4158/EP.4.1.1

##  激素治疗概述 

[女性倾向跨性别者的激素治疗][96]，又称为男跨女 (MtF) 激素替代疗法 (HRT) 或女性化激素疗法 (FHT) ，其目标是使身体产生 [女性化][97] 和 [去男性化][98] 的变化，并缓解 [性别焦虑][99]。用于实现这些变化的是 [性激素类药物][100]。女性倾向跨性别者使用 [雌激素][101]、[孕激素][102]，和 [抗雄药物][103] (AA)，以取代性腺性激素的分泌，并将激素状况从男性典型转向女性典型。

   [96]: https://en.wikipedia.org/wiki/Transgender_hormone_therapy_(male-to-female)
   [97]: https://en.wikipedia.org/wiki/Feminization_(biology)
   [98]: https://en.wikipedia.org/wiki/Demasculinization
   [99]: https://en.wikipedia.org/wiki/Gender_dysphoria
   [100]: https://en.wikipedia.org/wiki/Sex-hormonal_agent
   [101]: https://en.wikipedia.org/wiki/Estrogen_(medication)
   [102]: https://en.wikipedia.org/wiki/Progestogen_(medication)
   [103]: https://en.wikipedia.org/wiki/Antiandrogen

女性化激素治疗的目的是使雌二醇和睾酮水平达到正常女性范围。文献中普遍推荐的范围是雌二醇水平为 100 至 200 pg/mL，睾酮水平低于 50 ng/dL ([Wiki-Table][104])。然而，较高的 200 pg/mL 以上的雌二醇水平在女性化激素治疗中可以帮助抑制睾丸激素水平。血液中的性激素水平可以通过 [血检][105] 测量。这在女性化激素治疗是很有用的，可以确保激素状况已经按照治疗目标进行了令人满意的改变，特别是激素水平在女性范围内。

   [104]: https://en.wikipedia.org/wiki/Template:Target_ranges_for_hormone_levels_in_hormone_therapy_for_transgender_women
   [105]: https://en.wikipedia.org/wiki/Blood_test

###  性腺抑制 

在足够高的暴露量下，雌性激素和雄性激素能够完全抑制性腺性激素的产生，而孕激素本身能够部分但大幅度抑制性腺性激素的产生。更具体的说，对顺性别男性与女性倾向跨性别者的研究发现，雌二醇水平在 200 pg/mL 左右时一般能抑制睾酮水平约90% (至大约 50 ng/dL)，而雌二醇水平在 500 pg/mL 左右时，平均能抑制睾酮水平约95% (至大约 20–30 ng/dL) ([维基][106]; [维基-图表][107]). 雌二醇水平低于 200 pg/mL 也会抑制睾酮水平，尽管程度有所降低 ([Aly W., 2019][108]; [Aly W., 2019][109]; [Aly W., 2020][110])。单独使用孕激素可以抑制五至七成的睾酮水平 (至大约平均 150–300 ng/dL) ([Aly W., 2019][111]; [维基][112])。然而，在与少量的雌激素结合时，孕激素的抗促性腺激素作用可以产生协同效应，最大有效剂量的孕激素对睾酮水平的抑制增加到约95% (至大约 20–30 ng/dL) ([Aly W., 2019][113])。因此，与单独使用雌激素或孕激素相比，联合使用一种雌激素和一种孕激素可以用较低的剂量实现对睾酮水平的最大抑制。

   [106]: https://en.wikipedia.org/wiki/Pharmacodynamics_of_estradiol#Antigonadotropic_effects
   [107]: https://en.wikipedia.org/wiki/Template:Antigonadotropic_effects_of_estradiol
   [108]: https://transfemscience.org/articles/oral-e2-leinung-2018/
   [109]: https://transfemscience.org/articles/sublingual-e2-mpa-jain-2019/
   [110]: https://transfemscience.org/articles/e2-patches-de-ronde/
   [111]: https://transfemscience.org/articles/cpa-dosage/#testosterone-suppression-in-combination-with-estrogen
   [112]: https://en.wikipedia.org/wiki/Pharmacology_of_cyproterone_acetate#Antigonadotropic_effects
   [113]: https://transfemscience.org/articles/cpa-dosage/

![][114]

   [114]: https://transfemscience.org/assets/images/transfem-intro-pep-e2-t.png

图例：患有前列腺癌的男性在单次注射320毫克 [聚雌二醇磷酸酯][115] (PEP) (一种长效的雌二醇 [原药][116]) 后的雌二醇和睾酮水平 ([Stege et al., 1996][117])）。睾丸激素水平下降的峰值发生在雌二醇水平大于 200 pg/mL 时，约为90% (至大约 50 ng/dL)。

   [115]: https://en.wikipedia.org/wiki/Polyestradiol_phosphate
   [116]: https://en.wikipedia.org/wiki/Prodrug
   [117]: https://doi.org/10.1002/(SICI)1097-0045(199605)28:5%3C307::AID-PROS6%3E3.0.CO;2-8

雌激素和孕激素的抗促性腺激素作用在女性倾向跨性别者中被利用，以抑制性腺睾丸激素的产生，并达到与顺性别女性更一致的睾丸激素水平。应该注意的是，前面关于用雌激素和孕激素抑制睾丸激素的数字是平均数，在抑制睾丸激素方面，个人之间有很大差异。换句话说，有些人可能需要更多或更少的激素剂量来实现同样的睾丸激素水平下降。

###   效果时间线

在男性和女性的正常青春期，性激素暴露在几年内缓慢增加 ([Aly W., 2020][118])，性成熟逐渐发生。在非青少年的跨性别者中，一般会立即使用成人或更高剂量的激素，这可能导致第二性征的变化发生得更快。下表是从文献资料中转载的，略有修改，通常被引用为女性倾向跨性别者激素治疗效果的时间表 ([维基-图表][119])。它是基于临床经验、专家意见和对女性倾向跨性别者的临床研究的综合考虑。

   [118]: https://transfemscience.org/articles/hormone-levels-female-puberty/
   [119]: https://en.wikipedia.org/wiki/Template:Effects_of_feminizing_hormone_therapy_in_transgender_women

表格：常见剂量的激素治疗在成年女性倾向跨性别者的效果 ([维基-图表][120]): 

   [120]: https://en.wikipedia.org/wiki/Template:Effects_of_feminizing_hormone_therapy_in_transgender_women

| 效果 | 开始时间<sup>a</sup> | 完成时间<sup>a</sup> | 永久性 |
| --- | --- | --- | --- |
| 乳房发育 | 2–6 月 | 2–3 年 | 永久 |
| 毛发减少与生长减缓 | 3–12 月 | >3 年<sup>b</sup> | 可逆 |
| 头皮脱发的减少与逆转 | 1–3 月 | 1–2 年 | 可逆 |
| 皮肤软化，出油与痤疮减少 | 3–6 月 | 未知 | 可逆 |
| 女性化脂肪重分布 | 3–6 月 | 2–5 年 | 可逆 |
| 肌肉重量与强度减少 | 3–6 月 | 1–2 年<sup>c</sup> | 可逆 |
| 骨盆变宽和变圆<sup>d</sup> | 未知 | 未知 | 永久 |
| 情绪、情感和行为的变化 | 立即 | 未知 | 可逆 |
| 性欲和自发性勃起减少 | 1–3 月 | 3–6 月 | 可逆 |
| 勃起功能障碍和射精量减少 | 1–3 月 | 变化的 | 可逆 |
| 精子产量减少和不孕不育 | 未知 | >3 年 | 混合<sup>e</sup> |
| 睾丸体积缩小 | 3–6 月 | 2–3 年 | 未知 |
| 声音变化 (例如，音调/共鸣下降) | 无<sup>f</sup> | N/A | N/A |

<sup>a</sup> 由于遗传、饮食/营养、激素水平等因素，不同个体之间可能有很大差异。 <sup>b</sup> 激素治疗通常对女性倾向跨性别者的面部毛发密度影响不大。彻底去除面部和身体毛发可以通过以下方法实现： [激光脱毛][121] 和 [电解脱毛][122]。临时除毛可以使用 [刮毛][123]，[拔毛][124]，[蜜蜡脱毛][125]和其他方法。 <sup>c</sup> 可能因体育锻炼量的不同而有很大差异。 <sup>d</sup> 只发生在尚未完成生长板闭合的年轻人身上（在青春期后的人可能完全不会发生）。 <sup>e</sup> 只有雌激素，特别是大剂量的雌激素，似乎有可能导致长期或不可逆的不育；由抗雄激素引起的生育力受损通常在停药后容易恢复。 <sup>f</sup> [嗓音训练][126] 是实现声音女性化的有效方式。

   [121]: https://en.wikipedia.org/wiki/Laser_hair_removal
   [122]: https://en.wikipedia.org/wiki/Electrolysis
   [123]: https://en.wikipedia.org/wiki/Shaving
   [124]: https://en.wikipedia.org/wiki/Epilator
   [125]: https://en.wikipedia.org/wiki/Waxing
   [126]: https://en.wikipedia.org/wiki/Voice_training

##   具体的荷尔蒙治疗

用于女性倾向跨性别者治疗的药物包括雌激素、孕激素和抗雄激素。雌激素产生女性化并抑制睾酮水平，孕激素和抗雄激素可以帮助进一步抑制/ 阻止睾酮。雄激素有时候以低剂量用于睾酮低的跨性别者。这些药物有许多不同类型、好处与风险。

雌激素、孕激素和抗雄激素有不同的 [配方][127]，并可通过不同的 [给药途径][128] 使用。给药途径影响激素在体内的 [吸收][129]，[分布][130]，[代谢][131]，和 [消除][132]，产生 [生物利用度][133]、血液和特定组织中的激素水平以及 [代谢物][134] 的模式方面的明显差异。这些差异可能影响治疗。

   [127]: https://en.wikipedia.org/wiki/Drug_formulation
   [128]: https://en.wikipedia.org/wiki/Route_of_administration
   [129]: https://en.wikipedia.org/wiki/Absorption_(pharmacology)
   [130]: https://en.wikipedia.org/wiki/Distribution_(pharmacology)
   [131]: https://en.wikipedia.org/wiki/Metabolism
   [132]: https://en.wikipedia.org/wiki/Elimination_(pharmacology)
   [133]: https://en.wikipedia.org/wiki/Bioavailability
   [134]: https://en.wikipedia.org/wiki/Metabolite

表格：女性倾向跨性别者激素治疗的主要给药途径

| 途径 | 简称 | 描述 | 典型形式 |
| --- | --- | --- | --- |
| [口服给药][135] | 口服/ PO | 吞服 | 片剂、胶囊 |
| [舌下给药][136] | 舌下/ SL | 舌下含服并吸收 | 片剂 |
| [颊部给药][137] | 颊部/ BUC | 在脸颊或嘴唇下方保持并吸收 | 片剂 |
| [透皮给药][138] | 透皮/ TD | 涂抹在皮肤上并通过皮肤吸收 | 贴剂、凝胶、乳膏 |
| [直肠给药][139] | 直肠/ REC | 插入并被直肠吸收 | 栓剂 |
| [肌肉注射][140] | IM | 注射到肌肉中（例如，臀部、大腿、手臂） | 溶液 (vial/amp.) |
| [皮下注射][141] | SC | 注射到皮下脂肪中 | 溶液 (vial/amp.) |
| [皮下植入][142] | 植入/ SCi | 通过手术切口植入皮下脂肪 | 颗粒物 |

   [135]: https://en.wikipedia.org/wiki/Oral_administration
   [136]: https://en.wikipedia.org/wiki/Sublingual_administration
   [137]: https://en.wikipedia.org/wiki/Buccal_administration
   [138]: https://en.wikipedia.org/wiki/Transdermal
   [139]: https://en.wikipedia.org/wiki/Rectal_administration
   [140]: https://en.wikipedia.org/wiki/Intramuscular_injection
   [141]: https://en.wikipedia.org/wiki/Subcutaneous_injection
   [142]: https://en.wikipedia.org/wiki/Subcutaneous_implant

[阴道给药][143] 是顺性别女性使用激素类药物的主要途径。虽然通过天生的阴道给药对于女性倾向跨性别者是不可能的，但是 [新阴道][144] 给药对于完成了 [阴道成形术][145] 的人是一种选择。然而，新阴道的内膜不是天生女性的 [阴道上皮][146] ，而通常是皮肤或结肠，取决于所做的类型 ([阴茎内翻][147] 或 [乙状结肠][148])。因此，女性倾向跨性别者的新阴道给药在性质香可能与透皮或直肠途径（取决于新阴道的类型——相似，而非顺性别女性的阴道给药。根据一项研究，通过由 [腹膜][149]（腹部内膜）构建的新阴道吸收 雌二醇的情况与顺性别妇女阴道给药的情况相似 ([Willemsen et al., 1985][150])。

   [143]: https://en.wikipedia.org/wiki/Intravaginal_administration
   [144]: https://en.wiktionary.org/wiki/neovagina
   [145]: https://en.wikipedia.org/wiki/Vaginoplasty
   [146]: https://en.wikipedia.org/wiki/Vaginal_epithelium
   [147]: https://en.wikipedia.org/wiki/Penile_inversion_vaginoplasty
   [148]: https://en.wikipedia.org/wiki/Sigmoid_colon_vaginoplasty
   [149]: https://en.wikipedia.org/wiki/Peritoneum
   [150]: https://doi.org/10.1016/0028-2243(85)90036-X

###  雌激素

[雌二醇][151] 和 [雌二醇酯][152] 是被用于女性倾向跨性别者的雌激素。雌二醇酯的例子包括 [戊酸雌二醇][153] (EV; Progynova (补佳乐), Progynon Depot (日雌), Delestrogen)，[环戊酸雌二醇][154] (EC; Depo-Estradiol)，[庚酸雌二醇][155] (EEn) 和 [苯甲酸雌二醇][156] (EB; Progynon-B)。它们是雌二醇的 [原药][157]（即在体内转化为雌二醇），具有与雌二醇相同的生物活性。然而，它们当被注射使用时具有较长的 [使用时间][158]，因为注射部位的 [吸收][159] 较慢。这使得给药次数可以被减少。[磷酸聚雌二醇][160] (PEP; Estradurin) 是一种 [聚合物][161] 形式的雌二醇原药（即雌二醇分子的链接链）。它的 [代谢][162] 缓慢，持续时间很长。

   [151]: https://en.wikipedia.org/wiki/Estradiol_(medication)
   [152]: https://en.wikipedia.org/wiki/Estrogen_ester
   [153]: https://en.wikipedia.org/wiki/Estradiol_valerate
   [154]: https://en.wikipedia.org/wiki/Estradiol_cypionate
   [155]: https://en.wikipedia.org/wiki/Estradiol_enantate
   [156]: https://en.wikipedia.org/wiki/Estradiol_benzoate
   [157]: https://en.wikipedia.org/wiki/Prodrug
   [158]: https://en.wikipedia.org/wiki/Duration_of_action
   [159]: https://en.wikipedia.org/wiki/Absorption_(pharmacology)
   [160]: https://en.wikipedia.org/wiki/Polyestradiol_phosphate
   [161]: https://en.wikipedia.org/wiki/Polymer
   [162]: https://en.wikipedia.org/wiki/Metabolism

非 [生物相同的][163] 雌激素，如 [炔雌醇][164] (EE; 常用于 [避孕药][165])，[合成雌激素][166] (CEEs; Premarin (倍美力); 用于 [更年期激素治疗][167]) 与 [己烯雌酚][168] (DES; 已弃用)，与雌二醇相比，在肝脏中的代谢有阻力，对雌激素调节的 [肝脏合成][169] 有不成比例的影响 ([Aly W., 2020][170])。因此，它们有更大的健康风险，如 [血栓][171] 和相关的 [心血管问题][172]。因此，以及因为可能需要相对高剂量的雌激素来充分抑制性腺完整的女性倾向跨性别者的睾丸激素水平，非生物相同的雌激素最好不要用于激素治疗。

   [163]: https://en.wiktionary.org/wiki/bioidentical
   [164]: https://en.wikipedia.org/wiki/Ethinylestradiol
   [165]: https://en.wikipedia.org/wiki/Combined_oral_contraceptive_pill
   [166]: https://en.wikipedia.org/wiki/Conjugated_estrogens
   [167]: http://en.wikipedia.org/wiki/Menopausal_hormone_therapy
   [168]: https://en.wikipedia.org/wiki/Diethylstilbestrol
   [169]: https://en.wikipedia.org/wiki/Liver#Synthesis
   [170]: https://transfemscience.org/articles/estrogens-coagulation-blood-clots/
   [171]: https://en.wikipedia.org/wiki/Venous_thrombosis
   [172]: https://en.wikipedia.org/wiki/Cardiovascular_disease

雌激素可以以高剂量单独使用，以抑制睾丸激素水平进入女性范围。或者，可以用较低的剂量使用雌激素，使其与抗雄激素或孕激素结合，达到更多的 [生理性][173] 雌激素水平。这将导致雌激素部分抑制睾酮水平，并通过抗雄激素或孕激素进一步抑制或阻断剩余的睾酮。然而，在雌激素治疗中加入抗雄激素或孕激素，也将包括这些药物的副作用和风险。

   [173]: https://en.wiktionary.org/wiki/physiological

在没有雄性激素的情况下，雌性激素的女性化作用可以在低剂量下最高限度的发挥。更高剂量的雌激素，除了允许更强的睾丸激素抑制之外，并没有导致更好的女性化。事实上，有迹象表明，更高的剂量实际上可能会导致更糟糕的乳房发育。这个话题将在本网站未来的一篇文章中介绍。更高剂量的雌激素，包括雌二醇，也有更大的不良健康影响的风险，如血栓和心血管问题 ([Aly W., 2020][174])。因此，使用生理剂量的雌激素是最佳的。然而，大剂量的雌激素对抑制睾丸激素是有用的，在 [非口服][175] 雌二醇的情况下，绝对风险很低。它们也主要局限于有特定 [风险因素][176] 的人，包括年龄大、不运动、肥胖、同时使用孕激素、吸烟、手术和 [血栓性异常][177]。在没有相关风险因素的健康年轻人中，大剂量的非口服雌二醇 - 在合理范围内 - 的安全系数是可以被接受的 ([Aly W., 2020][174])。

   [174]: https://transfemscience.org/articles/estrogens-coagulation-blood-clots/
   [175]: https://en.wikipedia.org/wiki/Parenteral_administration
   [176]: https://en.wikipedia.org/wiki/Risk_factor
   [177]: http://en.wikipedia.org/wiki/Thrombophilia

####  雌二醇的途径、剂量和水平  

雌二醇及其酯类通常通过口服、舌下含服、透皮、肌肉注射和/或皮下注射等途径用于女性倾向跨性别者 ([维基][178])。

   [178]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_estradiol#Routes_of_administration

Oral estradiol is available in the form of tablets of estradiol or estradiol valerate. Administration of estradiol by the oral route has issues with bioavailability and often achieves relatively low estradiol levels, which can result in inadequate testosterone suppression depending on the antiandrogen ([Wiki][179]; [Leinung, 2014][180]; [Leinung et al., 2018][181]). Oral estradiol is not a favorable choice in the case of estrogen monotherapy due to the high estradiol levels required. Oral estradiol tablets can notably be taken sublingually instead of orally. Sublingual administration of estradiol tablets has as much as 5-fold higher bioavailability than when taken by the oral route ([Wiki][182]). However, sublingual estradiol has a very short duration ([Wiki][182]) and it may be advisable to take it in divided doses throughout the day to maintain steadier estradiol levels. Oral estradiol valerate tablets can be taken sublingually similarly to estradiol ([Wiki][183]; [Aly W., 2019][184]). Buccal administration of estradiol has similar properties to sublingual administration but is less often used and has not been studied as much ([Wiki][185]). 

   [179]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_estradiol#Oral_administration
   [180]: https://web.archive.org/web/20180304204640/http://press.endocrine.org/doi/abs/10.1210/endo-meetings.2014.RE.2.OR42-1
   [181]: https://doi.org/10.1089/trgh.2017.0035
   [182]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_estradiol#Sublingual_administration
   [183]: https://en.wikipedia.org/wiki/Estradiol_valerate#Sublingual_administration
   [184]: https://transfemscience.org/articles/sublingual-ev/
   [185]: https://en.wikipedia.org/wiki/Buccal_administration

Transdermal estradiol is available as patches, gel, emulsions, and sprays ([Wiki][186]). They are usually applied to skin sites such as the arms, abdomen, and buttocks. In the case of estrogen monotherapy, two to four maximum-dose patches or many pumps or packets of gel may be required to achieve estradiol levels sufficient for full testosterone suppression in transfeminine people ([Wiki][186]). Genital application of transdermal estradiol, specifically to the scrotum or neolabia, can result in much higher estradiol levels than application to conventional skin sites in this context ([Aly W., 2019][187]; [Aly W., 2019][188]). 

   [186]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_estradiol#Transdermal_administration
   [187]: https://transfemscience.org/articles/genital-e2-patches/
   [188]: https://transfemscience.org/articles/genital-e2-gel/

Injectable estradiol esters can be administered via either intramuscular or subcutaneous injection. In the case of intramuscular injection, possible injection sites include the [deltoid muscle][189] (upper arm), [vastus lateralis][190] and [rectus femoris muscles][191] (thigh), and [ventrogluteal muscle][192] (buttocks). Subcutaneous injection of estradiol esters, while less commonly used, is easier, less painful, and more convenient than the intramuscular route ([Wiki][193]). However, the maximum volume that can be injected subcutaneously is less than that which can be injected intramuscularly (depending on the site up to 1.5–3 mL and up to 2–5 mL, respectively) ([Hopkins, & Arias, 2013][194]; [Usach et al., 2019][195]). Injections of estradiol esters can easily achieve high levels of estradiol and, depending on the estradiol ester in question, last for days to weeks. An injection of PEP, which in contrast to other estradiol esters should always be administered by intramuscular injection, lasts for months. However, the availability of PEP is very limited, with its use mostly restricted to the Nordic region of Europe ([Wiki][196]). 

   [189]: https://en.wikipedia.org/wiki/Deltoid_muscle
   [190]: https://en.wikipedia.org/wiki/Vastus_lateralis_muscle
   [191]: https://en.wikipedia.org/wiki/Rectus_femoris_muscle
   [192]: http://en.wikipedia.org/wiki/Ventrogluteal_muscle
   [193]: http://en.wikipedia.org/wiki/Pharmacokinetics_of_estradiol#Subcutaneous_injection
   [194]: https://www.oncologynurseadvisor.com/home/hot-topics/chemotherapy/large-volume-im-injections-%E2%80%A8a-review-of-best-practices/
   [195]: https://doi.org/10.1007/s12325-019-01101-6
   [196]: https://en.wikipedia.org/wiki/Polyestradiol_phosphate#Availability

Non-oral routes, although less convenient than the oral route, are preferred, because oral estradiol results in excessive levels of estradiol in the liver and has a disproportionate impact on estrogen-modulated liver protein synthesis ([Aly W., 2020][197]). Particularly at the high doses of estrogens that may be required to suppress testosterone levels in transfeminine people, this may increase the risk of health issues like blood clots and cardiovascular problems. The health concerns of estradiol are largely allayed if it is taken non-orally at reasonable doses. 

   [197]: https://transfemscience.org/articles/estrogens-coagulation-blood-clots/

Table: Available forms and recommended doses of estradiol (for adults/non-adolescents): 

| Medication | Route | Form | Dosage |
| --- | --- | --- | --- |
| [Estradiol][198] | Oral | Tablets | 2–10 mg/day |
| | Sublingual or buccal | Tablets | 0.5–2 mg 1–4x/day |
| | Transdermal | Patches | 50–300 μg/day |
| | Transdermal | Gel | 2–6 mg/day |
| | SC implant | Pellet | 25–150 mg/6 months |
| [Estradiol valerate][199] | Oral | Tablets | 2–10 mg/day |
| | Sublingual or buccal | Tablets | 0.5–2 mg 1–4x/day |
| | IM or SC injection | Oil solution | 2–6 mg/week; or 1.5–4 mg/5 days |
| [Estradiol cypionate][200] | IM or SC injection | Oil solution | 2–6 mg/week |
| [Estradiol benzoate][201] | IM or SC injection | Oil solution | 1–3 mg 2x/week |
| [Estradiol enanthate][202] | IM or SC injection | Oil solution | 4–12 mg/2 weeks |
| [Polyestradiol phosphate][203] | IM injection | Water solution | 40–160 mg/month<sup>a</sup> |

   [198]: https://en.wikipedia.org/wiki/Estradiol_(medication)
   [199]: https://en.wikipedia.org/wiki/Estradiol_valerate
   [200]: https://en.wikipedia.org/wiki/Estradiol_cypionate
   [201]: https://en.wikipedia.org/wiki/Estradiol_benzoate
   [202]: https://en.wikipedia.org/wiki/Estradiol_enanthate
   [203]: https://en.wikipedia.org/wiki/Polyestradiol_phosphate

<sup>a</sup> In the case of polyestradiol phosphate, a loading dose of, e.g., 240 to 320 mg, can be employed for the first one or two injections to reach steady state levels of estradiol more quickly.

For estrogen levels with different forms, routes, and doses of estradiol, see the tables [here][204] and [here][205] and the graphs [here][206]. 

   [204]: https://transfemscience.org/articles/e2-equivalent-doses/
   [205]: https://en.wikipedia.org/wiki/Template:Plasma_estrogen_levels_after_a_single_dose_of_estradiol_by_different_routes
   [206]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_estradiol

There is high variability between individuals in the levels of estradiol achieved during estradiol therapy. That is, estradiol levels during treatment with the same dosage of estradiol can differ widely between individuals. This variability is greatest with the oral and transdermal routes. As such, the doses of estradiol recommended are not absolute and should be individualized in conjunction with blood work on a case-by-case basis. It should also be noted that estradiol levels can vary considerably from one blood test to another, most importantly with the sublingual and injected routes. However, this variation is predictable, and can be minimized with proper timing of blood tests. 

After removal of the gonads, estrogen doses can be lowered or adjusted to approximate normal female physiological exposure. The average production of estradiol in premenopausal women is about 6 mg over the course of a single menstrual cycle (i.e., one month) ([Rosenfield et al., 2008][207]). 

   [207]: https://scholar.google.com/scholar?cluster=9979206541205334235

###  Progestogens 

[Progestogens][208] include [progesterone][209] and [progestins][210]. Progestins are [synthetic][211] progestogens derived from [structural modification][212] of progesterone or testosterone. Examples of some major progestins include [medroxyprogesterone acetate][213] (MPA; Provera, Depo-Provera), [norethisterone][214] (NET; many brand names), [dydrogesterone][215] (Duphaston), and [drospirenone][216] (Slynd, Yasmin) ([Aly W., 2019][217]). There are dozens of different progestins and these progestins can be divided into a variety of different structural classes with varying properties ([Wiki-Table][218]). Progestins were developed because they have a more favorable [disposition in the body][219] than progesterone for use as medications. Only a few clinically used progestins have been used in transfeminine hormone therapy, although almost all progestogens have the same progestogenic actions and theoretically any progestogen could be employed. 

   [208]: https://en.wikipedia.org/wiki/Progestogen_(medication)
   [209]: https://en.wikipedia.org/wiki/Progesterone_(medication)
   [210]: https://en.wikipedia.org/wiki/Progestin
   [211]: https://en.wikipedia.org/wiki/Synthetic_compound
   [212]: https://en.wikipedia.org/wiki/Molecular_modification
   [213]: https://en.wikipedia.org/wiki/Medroxyprogesterone_acetate
   [214]: https://en.wikipedia.org/wiki/Norethisterone
   [215]: https://en.wikipedia.org/wiki/Dydrogesterone
   [216]: https://en.wikipedia.org/wiki/Drospirenone
   [217]: https://transfemscience.org/articles/drospirenone-approval/
   [218]: https://en.wikipedia.org/wiki/Template:Progestogens_marketed_for_clinical_or_veterinary_use
   [219]: http://en.wikipedia.org/wiki/Pharmacokinetics

Most progestogens also have [off-target activities][220] that may be desirable or undesirable depending on the action in question ([Kuhl, 2005][221]; [Stanczyk et al., 2013][222]; [Wiki][223]; [Wiki-Table][224]). Progesterone has [neurosteroid][225] activities that can result in a variety of brain effects not shared by progestins. MPA as well as NET and its derivatives have weak androgenic activity—which is unfavorable in the context of transfeminine hormone therapy. NET and certain related progestins produce EE as a [metabolite][226] at high doses and hence can produce EE-like estrogenic effects—including risk of blood clots and cardiovascular problems. Other off-target activities of progestogens include antiandrogenic, [glucocorticoid][227], and [antimineralocorticoid][228] activities. These actions can produce changes in therapeutic effectiveness (e.g., androgen suppression or blockade), side effects, and health risks. 

   [220]: https://en.wikipedia.org/wiki/Off-target_activity
   [221]: https://doi.org/10.1080/13697130500148875
   [222]: https://doi.org/10.1210/er.2012-1008
   [223]: https://en.wikipedia.org/wiki/Progestogen_(medication)#Pharmacodynamics
   [224]: https://en.wikipedia.org/wiki/Template:Pharmacodynamics_of_progestogens
   [225]: https://en.wikipedia.org/wiki/Neurosteroid
   [226]: https://en.wikipedia.org/wiki/Metabolite
   [227]: https://en.wikipedia.org/wiki/Glucocorticoid
   [228]: https://en.wikipedia.org/wiki/Antimineralocorticoid

The addition of progestogens to estrogen therapy has been associated with a number of unfavorable health effects. These include increased risk of blood clots ([Wiki][229]; [Aly W., 2020][230]), [coronary heart disease][231] ([Wiki][232]), and breast cancer ([Wiki][233]; [Aly W., 2020][234]). High doses of progestogens are also associated with increased risk of certain non-cancerous brain tumors including [meningiomas][235] and [prolactinomas][236] ([Wiki][237]; [Aly W., 2020][238]). The coronary heart disease risk may be due to changes in [blood lipids][239] caused by the weak androgenic activity of specific progestogens, but the rest of the aforementioned risks are probably due to their progestogenic activity (Stanczyk et al., 2013; [Jiang & Tian, 2017][240]). Aside from health risks, progestogens have also been associated with adverse mood changes ([Wiki][241]; [Wiki][242]). However, these effects are controversial and are not well-supported by evidence ([Wiki][241]; [Wiki][242]). Progestogens are otherwise generally well-tolerated and produce few to no side effects. 

   [229]: https://en.wikipedia.org/wiki/Progestogen_(medication)#Blood_clots
   [230]: https://transfemscience.org/articles/estrogens-coagulation-blood-clots/
   [231]: https://en.wikipedia.org/wiki/Coronary_artery_disease
   [232]: https://en.wikipedia.org/wiki/Progestogen_(medication)#Cardiovascular_health
   [233]: https://en.wikipedia.org/wiki/Progestogen_(medication)#Side_effects
   [234]: https://transfemscience.org/articles/breast-cancer/
   [235]: http://en.wikipedia.org/wiki/Meningioma
   [236]: http://en.wikipedia.org/wiki/Prolactinoma
   [237]: https://en.wikipedia.org/wiki/Side_effects_of_cyproterone_acetate#Brain_tumors
   [238]: https://transfemscience.org/articles/cpa-meningioma/
   [239]: https://en.wikipedia.org/wiki/Blood_lipids
   [240]: https://doi.org/10.1186/s12944-017-0612-5
   [241]: https://en.wikipedia.org/wiki/Progestogen_(medication)#Mood_changes
   [242]: https://en.wikipedia.org/wiki/Medroxyprogesterone_acetate#Mood_changes

In contrast to progestins, progesterone has no unfavorable off-target activities. Moreover, the addition of oral progesterone to estrogen therapy has not been associated with increased risk of blood clots ([Wiki][243]). In addition, oral progesterone seems to have less risk of breast cancer than progestins with short-term therapy although notably not with longer-term exposure ([Wiki][244]; [Aly W., 2020][245]). As such, it has been suggested that progesterone, for reasons that have yet to be fully elucidated, may be a safer progestogen than progestins and that it should be preferred for progestogen therapy. However, the seemingly better safety of progesterone may simply be an artifact of the very low progesterone levels that occur with [oral][246] progesterone and hence of dosage ([Aly W., 2018][247]; [Wiki][248]). [Non-oral][249] progesterone at doses resulting in full progestogenic strength has never been properly evaluated in terms of health outcomes and may have the same risks as progestins ([Aly W., 2018][247]; [Wiki][248]). 

   [243]: https://en.wikipedia.org/wiki/Progesterone_(medication)#Blood_clots
   [244]: https://en.wikipedia.org/wiki/Progesterone_(medication)#Breast_cancer
   [245]: https://transfemscience.org/articles/breast-cancer/
   [246]: https://en.wikipedia.org/wiki/Oral_administration
   [247]: https://transfemscience.org/articles/oral-p4-low-levels/
   [248]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_progesterone#Clinical_progestogenic_potency_and_effects
   [249]: https://en.wikipedia.org/wiki/Parenteral_administration

Progestogens are of no clear or known benefit for feminization or breast development in transfeminine people aside from helping with testosterone suppression. While some transfeminine people [anecdotally][250] claim to experience improved breast development with progestogens, an involvement of these agents in breast size or shape is controversial and not supported by theory or evidence at present ([Wiki][251]; [Aly W., 2020][252]; [Aly W., 2020][253]). It’s possible that premature introduction of progestogens may actually have an unfavorable influence on breast development ([Aly W., 2019][254]). Many transfeminine people have also anecdotally claimed that progestogens have a beneficial effect on their sexual desire. However, a review of the literature showed that neither progesterone nor progestins positively influence sexual desire ([Aly W., 2020][255]). Instead, the available evidence indicates the opposite—an inhibitory influence of progestogens on sexual desire—although this may be specific to high doses ([Aly W., 2020][255]). 

   [250]: https://en.wikipedia.org/wiki/Anecdotal_evidence
   [251]: https://en.wikipedia.org/wiki/Transgender_hormone_therapy_(male-to-female)#Progestogens
   [252]: https://transfemscience.org/articles/p4-breast-dev-puberty/
   [253]: https://transfemscience.org/articles/cais-breast-dev-p4/
   [254]: https://transfemscience.org/articles/progestogens-suboptimal-breast-dev-excerpts/
   [255]: https://transfemscience.org/articles/progestogens-sexual-desire/

Due to their lack of influence on feminization and breast development and their adverse effects and health risks, progestogens are not routinely used in transfeminine hormone therapy at present. There is however a major exception to this in the form of [cyproterone acetate][256] (CPA; Androcur), an antiandrogen which is widely used in transfeminine hormone therapy and also happens to be a powerful progestogen at typical therapeutic doses. CPA will be described in the section below on antiandrogens. Although progestogens have various health risks, cisgender women of course have progesterone and the absolute risks of progestogens are very low in healthy young people. Risks like breast cancer also take many years to develop. And the testosterone suppression provided by progestogens can be very useful in transfeminine people. A limited duration of progestogen therapy, for instance a few years to help suppress testosterone levels before gonadectomy, may be quite acceptable in transfeminine people. 

   [256]: https://en.wikipedia.org/wiki/Cyproterone_acetate

####  Routes, Doses, and Levels of Progesterone and Progestins 

Progesterone can be used in transfeminine people by the oral route, by the [rectal][257] route, or by intramuscular or subcutaneous injection ([Wiki][258]). Progestins are usually used by the oral route but certain progestins are also available in injectable formulations. 

   [257]: https://en.wikipedia.org/wiki/Rectal_administration
   [258]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_progesterone#Routes_of_administration

Levels of progesterone with the oral route have been found using state-of-the-art assays (LC–MS) to be very low (<2 ng/dL at 100 mg/day) and inadequate for satisfactory progestogenic effects ([Wiki][259]; [Aly W., 2018][260]). In accordance, even high doses of oral progesterone showed no antigonadotropic effect in cisgender men ([Wiki][261]). This is in major contrast to non-oral progesterone and to progestins. Additionally, oral progesterone is excessively converted into potent neurosteroid metabolites like allopregnanolone and [pregnanolone][262], and this can result in undesirable [alcohol][263]-like side effects such as sedation, cognitive/memory impairment, and mood changes ([Wiki][264]; [Wiki][265]). As such, while inconvenient, non-oral routes are preferable in the case of progesterone similarly to estradiol. Conversely, progestins have high oral bioavailability and are resistant to metabolism in the liver. In contrast to the ERs, PRs are expressed minimally or not at all in the liver ([Lax, 1987][266]). For these reasons, there are no apparent problems with the oral route in the case of progestins. 

   [259]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_progesterone#Oral_administration
   [260]: https://transfemscience.org/articles/oral-p4-low-levels/
   [261]: https://en.wikipedia.org/wiki/Pharmacodynamics_of_progesterone#Antigonadotropic_effects
   [262]: https://en.wikipedia.org/wiki/Pregnanolone
   [263]: https://en.wikipedia.org/wiki/Alcohol_(drug)
   [264]: https://en.wikipedia.org/wiki/Pharmacodynamics_of_progesterone#Neurosteroid_effects
   [265]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_progesterone#First-pass_effect_and_neurosteroids
   [266]: https://doi.org/10.1016/0022-4731(87)90198-1

Sublingual progesterone tablets exist but are only available in a couple of Eastern European countries ([Wiki][267]). In contrast to estradiol, oral progesterone is formulated as oil-filled capsules. This makes them difficult and unpleasant to use by the sublingual route. 

   [267]: https://en.wikipedia.org/wiki/Progesterone_(medication)#Availability

Progesterone can be used rectally in the form of suppositories. Oral micronized progesterone capsules can be taken rectally and this can allow for much higher progesterone levels than would be achieved orally ([Aly W., 2018][268]). While certainly inconvenient, rectal use is probably the best route of administration for progesterone for transfeminine people. 

   [268]: https://transfemscience.org/articles/oral-p4-rectally/

Progesterone by injection is available in both intramuscular and subcutaneous forms. However, injectable progesterone has a relatively short duration and must be given once every one to three days. This makes it too inconvenient to use for most people. Unlike with estradiol, [progesterone esters][269] with longer durations than progesterone itself by injection are not chemically possible. Injectable progestins, on the other hand, have durations ranging from weeks to months. 

   [269]: https://en.wikipedia.org/wiki/Progestogen_ester

Table: Available forms and recommended doses of progestogens: 

| Medication | Route | Form | Dosage |
| --- | --- | --- | --- |
| [Progesterone][270] | Oral | Oil-filled capsules | 100–300 mg 1–2x/day |
| | Rectal | Suppositories; Oil-filled capsules | 100–200 mg 1–2x/day |
| | IM injection | Oil solution | 25–75 mg/1–3 days |
| | SC injection | Water solution | 25 mg/day |
| [Progestins][271] | Oral; IM or SC injection | Tablets; Oil solution; Water solution | Various |


   [270]: https://en.wikipedia.org/wiki/Progesterone_(medication)
   [271]: https://en.wikipedia.org/wiki/Progestin

For progesterone levels with different forms, routes, and doses of progesterone, see the table [here][272] (only LC–MS and IA + CS assays for oral progesterone) and the graphs [here][273]. 

   [272]: https://en.wikipedia.org/wiki/Template:Plasma_progesterone_levels_after_a_single_dose_of_progesterone_by_different_routes
   [273]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_progesterone

As with estradiol, there is high variability between individuals in progesterone levels. Conversely, there is relatively little variability between individuals in the case of progestins. 

After removal of the gonads, progestogen doses can be lowered or adjusted to approximate normal female physiological exposure or they can be discontinued entirely. 

###  Antiandrogens 

Aside from estrogens and progestogens, there is another class of hormonal medications used in transfeminine hormone therapy known as antiandrogens (AAs). These medications nullify the effects of androgens in the body. They work by a variety of different mechanisms of action and include AR [antagonists][274], [antigonadotropins][275], and [androgen synthesis inhibitors][276]. 

   [274]: https://en.wikipedia.org/wiki/Receptor_antagonist
   [275]: https://en.wikipedia.org/wiki/Antigonadotropin
   [276]: https://en.wikipedia.org/wiki/Antiandrogen#Androgen_synthesis_inhibitors

AR antagonists work by directly blocking the effects of androgens. They bind to the AR without activating it, thereby displacing androgens from the receptor. AR antagonists include [steroidal antiandrogens][277] (SAAs) like [spironolactone][278] (Aldactone) and [cyproterone acetate][279] (CPA; Androcur) and [nonsteroidal antiandrogens][280] (NSAAs) like [bicalutamide][281] (Casodex). 

   [277]: https://en.wikipedia.org/wiki/Steroidal_antiandrogen
   [278]: https://en.wikipedia.org/wiki/Spironolactone
   [279]: https://en.wikipedia.org/wiki/Cyproterone_acetate
   [280]: https://en.wikipedia.org/wiki/Nonsteroidal_antiandrogen
   [281]: https://en.wikipedia.org/wiki/Bicalutamide

Antigonadotropins suppress the gonadal production of androgens by inhibiting the GnRH-mediated secretion of gonadotropins from the pituitary gland. They include estrogens and progestogens. In addition, [GnRH agonists][282] such as [leuprorelin][283] (Lupron) and [GnRH antagonists][284] such as [elagolix][285] (Orilissa) act similarly and could be regarded as antigonadotropins. 

   [282]: https://en.wikipedia.org/wiki/Gonadotropin-releasing_hormone_agonist
   [283]: https://en.wikipedia.org/wiki/Leuprorelin
   [284]: https://en.wikipedia.org/wiki/Gonadotropin-releasing_hormone_antagonist
   [285]: https://en.wikipedia.org/wiki/Elagolix

Androgen synthesis inhibitors inhibit the enzyme-mediated synthesis of androgens. They include [5α-reductase inhibitors][286] (5α-RIs) like [finasteride][287] (Propecia) and [dutasteride][288] (Avodart). There are also other types of androgen synthesis inhibitors, for instance potent [17α-hydroxylase/17,20-lyase inhibitors][289] like [ketoconazole][290] (Nizoral) and [abiraterone acetate][291] (Zytiga). However, these other agents have limitations (e.g., [toxicity][292], cost, lack of experience) and are not used in transfeminine hormone therapy. 

   [286]: https://en.wikipedia.org/wiki/5%CE%B1-Reductase_inhibitor
   [287]: https://en.wikipedia.org/wiki/Finasteride
   [288]: https://en.wikipedia.org/wiki/Dutasteride
   [289]: https://en.wikipedia.org/wiki/CYP17A1_inhibitor
   [290]: https://en.wikipedia.org/wiki/Ketoconazole
   [291]: https://en.wikipedia.org/wiki/Abiraterone_acetate
   [292]: https://en.wikipedia.org/wiki/Toxicity

Although antigonadotropins and androgen synthesis inhibitors certainly have antiandrogenic effects secondary to decreased androgen levels, they are not usually referred to as “antiandrogens”. Instead, the term “antiandrogen” is most commonly reserved to describe AR antagonists. 

####  Androgen Receptor Antagonists 

AR antagonists act by directly blocking the effects of androgens. Unlike antigonadotropins and androgen synthesis inhibitors, they do not work by suppressing androgen levels. However, some AR antagonists also have additional actions that result in decreased androgen levels. Due to the nature of their mechanism of action as competitive blockers of androgens, the antiandrogenic efficacy of AR antagonists is both highly dose-dependent and fundamentally dependent on testosterone levels. AR antagonists tend to have relatively low [affinity][293] for the AR, and relatively high doses by weight may be required for satisfactory prevention of the effects of testosterone—especially in the context of male-range testosterone levels ([Aly W., 2019][294]). In any case, AR antagonists can be very useful when testosterone levels are incompletely but markedly suppressed (e.g., <200 ng/dL). Because AR antagonists do not work by lowering testosterone levels, blood work is less informative for them compared to antiandrogens that suppress testosterone levels. 

   [293]: https://en.wikipedia.org/wiki/Affinity_(pharmacology)
   [294]: https://transfemscience.org/articles/bica-dosage/

The AR antagonists spironolactone, bicalutamide, and CPA are all taken orally in the form of tablets. 

Table: Available forms and recommended doses of antiandrogens: 

| Medication | Type | Route | Form | Dosage |
| --- | --- | --- | --- | --- |
| [Spironolactone][295] | AR antagonist; Weak androgen synthesis inhibitor | Oral | Tablets | 100–200 mg 1–2x/day<sup>a</sup> |
| [Bicalutamide][296] | AR antagonist | Oral | Tablets | 12.5–50 mg/day<sup>a</sup> |
| [Cyproterone acetate][297] | Progestogen; AR antagonist | Oral | Tablets | 2.5–12.5 mg/day (total)<sup>b</sup> |

   [295]: https://en.wikipedia.org/wiki/Spironolactone
   [296]: https://en.wikipedia.org/wiki/Bicalutamide
   [297]: https://en.wikipedia.org/wiki/Cyproterone_acetate

<sup>a</sup> For the AR antagonists spironolactone and bicalutamide, it is assumed that testosterone levels are substantially suppressed (≤200 ng/dL). If not, higher doses may be warranted. <sup>b</sup> For CPA, one-quarter of a 10-mg tablet to one full 10-mg tablet per day (2.5–10 mg/day) _or_ a quarter of a 50-mg tablet every other day or every 2 to 3 days (4.2–12.5 mg/day). A dosage of 5 to 12.5 mg/day is likely to ensure maximal testosterone suppression while lower doses may be less effective.

####  Spironolactone 

Spironolactone is a relatively weak AR antagonist ([Wiki][298]). It is also a weak androgen synthesis inhibitor in addition to AR antagonist—specifically via 17α-hydroxylase/17,20-lyase inhibition ([Wiki][298]). However, it shows limited and highly inconsistent effects on testosterone levels and its primary mechanism of action appears to be via AR blockade ([Aly W., 2018][299]; [Aly W., 2020][300]). Due to its relatively weak AR antagonism, spironolactone is best-suited for blocking female-range or somewhat higher testosterone levels. 

   [298]: https://en.wikipedia.org/wiki/Spironolactone#Pharmacodynamics
   [299]: https://transfemscience.org/articles/spiro-hormone-levels-men-transfem/
   [300]: https://transfemscience.org/articles/spiro-hormone-levels-women/

Spironolactone has [antimineralocorticoid][301] side effects and has a risk of rare but potentially life-threatening [hyperkalemia][302] (high potassium levels) in those with specific risk factors ([Wiki][303]). Monitoring of blood potassium levels during spironolactone therapy is advisable in those with risk factors for high potassium levels, but appears to not be necessary in people without such risk factors ([Plovanich et al., 2015][304]). Risk factors for high potassium levels include old age, kidney disease, concomitant use of other potassium-elevating drugs, and intake of potassium supplements. 

   [301]: https://en.wikipedia.org/wiki/Antimineralocorticoid
   [302]: https://en.wikipedia.org/wiki/Hyperkalemia
   [303]: https://en.wikipedia.org/wiki/Spironolactone#High_potassium_levels
   [304]: https://www.doi.org/10.1001/jamadermatol.2015.34

####  Bicalutamide 

Bicalutamide is a potent and highly selective AR antagonist ([Wiki][305]). Due to its relatively high potency, bicalutamide is able at higher doses to substantially block male-range testosterone levels ([Aly W., 2019][306]). Owing to its selectivity for the AR, bicalutamide has no off-target hormonal activity and has almost no side effects in women ([Erem, 2013][307]; [Moretti et al., 2018][308]). As a selective AR antagonist, bicalutamide does not decrease testosterone levels ([Wiki][309]). 

   [305]: https://en.wikipedia.org/wiki/Bicalutamide#Pharmacodynamics
   [306]: https://transfemscience.org/articles/bica-dosage/
   [307]: https://www.tandfonline.com/doi/abs/10.2143/ACB.3267
   [308]: https://doi.org/10.1210/jc.2017-01186
   [309]: https://en.wikipedia.org/wiki/Pharmacology_of_bicalutamide#Influences_on_hormone_levels

Bicalutamide has mostly been used to treat men with prostate cancer, but has also been used to treat other androgen-dependent conditions such as excessive facial and/or body hair in women and is becoming increasingly adopted for use in transfeminine people ([Aly W., 2020][310]; [Wiki][311]). 

   [310]: https://transfemscience.org/articles/bica-adoption/
   [311]: https://en.wikipedia.org/wiki/Medical_uses_of_bicalutamide#Transgender_hormone_therapy

Bicalutamide has a small risk of [liver toxicity][312] ([Wiki][313]; [Aly W., 2020][314]) and [lung toxicity][315] ([Wiki][316]). Liver monitoring is advisable during bicalutamide therapy. Older AR antagonists related to bicalutamide like [flutamide][317] (Eulexin) and [nilutamide][318] (Anandron, Nilandron) have much greater health risks in comparison and should not be used in transfeminine hormone therapy. 

   [312]: http://en.wikipedia.org/wiki/Liver_toxicity
   [313]: https://en.wikipedia.org/wiki/Side_effects_of_bicalutamide#Liver_toxicity
   [314]: https://transfemscience.org/articles/bica-adoption/
   [315]: https://en.wikipedia.org/wiki/Lung_disease
   [316]: https://en.wikipedia.org/wiki/Side_effects_of_bicalutamide#Lung_toxicity
   [317]: https://en.wikipedia.org/wiki/Flutamide
   [318]: https://en.wikipedia.org/wiki/Nilutamide

####  Cyproterone Acetate 

CPA is a progestogen that at much higher doses also acts as an AR antagonist ([Aly W., 2019][319]). It has been used at relatively high doses in transfeminine people to take advantage of its AR antagonism ([Aly W., 2019][319]). As a result of the strong progestogenic exposure that occurs with typical doses of CPA, the medication substantially suppresses testosterone levels in addition to its AR antagonism ([Aly W., 2019][319]). Relatively low doses of CPA (e.g., 5–10 mg/day) are able to maximally suppress testosterone levels in combination with even low doses of an estrogen ([Aly W., 2019][319]). Due to a variety of dose-dependent risks with CPA, doses of the medication have come down substantially in recent years. Lower doses of CPA are likely to be purely progestogenic and have minimal or no significant AR antagonism. However, the AR antagonism of higher doses is unnecessary since the combination of CPA with estradiol results in suppression of testosterone levels well into the female range. 

   [319]: https://transfemscience.org/articles/cpa-dosage/

CPA has been reported to produce fatigue and slight weight gain as side effects ([Belisle & Love, 1986][320]; [Hammerstein, 1990][321]). It may result in sexual dysfunction ([Wiki][322]; [Aly W., 2019][323]) and have a small risk of depressive mood changes ([Wiki][324]; [Aly W., 2019][325]). CPA produces pregnancy-like breast changes ([Kanhai et al., 2000][326]) and sometimes causes [lactation][327] as a side effect in transfeminine people ([Gooren, Harmsen-Louman, & van Kessel, 1985][328]; [Schlatterer et al., 1998][329]; [Bazarra-Castro, 2009][330]). As with other progestogens, the addition of low doses of CPA to estrogen therapy is associated with increased risk of blood clots and breast cancer ([Wiki][331]; [Wiki][332]; [Aly W., 2020][333]). Higher doses of CPA appear to have a greater risk of blood clots than low doses ([Wiki][331]). CPA is also associated with [high prolactin levels][334] ([Wiki][322]) and with certain non-cancerous brain tumors including prolactinomas and meningiomas ([Wiki][335]; [Aly W., 2020][336]). High doses of CPA are associated with [abnormal liver changes][337] and have resulted in rare cases of liver toxicity ([Wiki][338]). This probably isn’t an issue at doses of less than 20 mg/day however ([Wiki][338]). Monitoring of [prolactin][339] levels to detect prolactinomas and monitoring of liver function to detect liver toxicity is advisable during CPA therapy. The side effects and risks of CPA may be minimized by using the lowest effective dosage, which is much lower than what has conventionally been used ([Aly W., 2019][340]). 

   [320]: https://doi.org/10.1016/S0015-0282(16)49873-0
   [321]: https://doi.org/10.1007/978-3-642-74612-3_35
   [322]: https://en.wikipedia.org/wiki/Side_effects_of_cyproterone_acetate#High_prolactin_levels
   [323]: https://transfemscience.org/articles/progestogens-sexual-desire/
   [324]: https://en.wikipedia.org/wiki/Side_effects_of_cyproterone_acetate#Depression
   [325]: https://transfemscience.org/articles/cpa-depression/
   [326]: https://doi.org/10.1097/00000478-200001000-00009
   [327]: http://en.wikipedia.org/wiki/Lactation
   [328]: https://doi.org/10.1111/j.1365-2265.1985.tb01081.x
   [329]: https://doi.org/10.1023/A:1018704630036
   [330]: https://doi.org/10.5282/edoc.9984
   [331]: https://en.wikipedia.org/wiki/Side_effects_of_cyproterone_acetate#Blood_clots
   [332]: https://en.wikipedia.org/wiki/Side_effects_of_cyproterone_acetate#Breast_cancer
   [333]: https://transfemscience.org/articles/breast-cancer/
   [334]: http://en.wikipedia.org/wiki/Hyperprolactinemia
   [335]: https://en.wikipedia.org/wiki/Side_effects_of_cyproterone_acetate#Brain_tumors
   [336]: https://transfemscience.org/articles/cpa-meningioma/
   [337]: https://en.wikipedia.org/wiki/Elevated_transaminases
   [338]: https://en.wikipedia.org/wiki/Side_effects_of_cyproterone_acetate#Liver_toxicity
   [339]: http://en.wikipedia.org/wiki/Prolactin
   [340]: https://transfemscience.org/articles/cpa-dosage/

CPA is notably not approved for use in the United States, but is available in most other countries. 

####  5α-Reductase Inhibitors 

Testosterone is converted into DHT within certain tissues in the body ([Swerdloff et al., 2017][341]). DHT is an androgen metabolite of testosterone with several-fold higher activity than testosterone. The transformation of testosterone into DHT is mediated by the enzyme [5α-reductase][342]. The tissues in which 5α-reductase is present and testosterone is converted into DHT are limited and most importantly include the skin, hair follicles, and prostate gland. Although DHT is more potent than testosterone, it has minimal biological role as a circulating hormone ([Horton, 1992][343]; Swerdloff et al., 2017). Instead, testosterone serves as the main circulating androgen, and the role of DHT is from metabolism of testosterone into DHT within tissues. 

   [341]: https://doi.org/10.1210/er.2016-1067
   [342]: https://en.wikipedia.org/wiki/5%CE%B1-Reductase
   [343]: https://doi.org/10.1002/j.1939-4640.1992.tb01621.x

5α-RIs inhibit 5α-reductase and thereby block the conversion of testosterone into DHT. This results in marked decreases in circulating and within-tissue levels of DHT. Due to DHT’s role as a mediator in tissues rather than circulating hormone, the antiandrogenic efficacy of 5α-RIs is limited. This is exemplified by the fact that they are well-tolerated in cisgender men and don’t cause notable demasculinization in them ([Hirshburg, 2016][344]). The medical use of 5α-RIs is mainly restricted to the treatment of scalp hair loss in men and women, hirsutism (excessive facial/body hair) in women, and [prostate enlargement][345] in men. They might also be useful for acne in women, but evidence of this is very limited ([Wiki][346]). Due to their specificity, 5α-RIs are inappropriate as general antiandrogens in transfeminine people. Moreover, DHT levels decrease in tandem with testosterone levels with suppression of testosterone production in transfeminine hormone therapy, and routine use of 5α-RIs in transfeminine people with testosterone levels within the female range can be considered unnecessary ([Irwig, 2020][347]). In any case, 5α-RIs may be useful in transfeminine people on hormone therapy who have persistent body hair growth or scalp hair loss—as they have been shown to be in cisgender women ([Barrionuevo et al., 2018][348]). However, it is notable that evidence is better for AR antagonists for such indications ([van Zuuren et al., 2015][349]). This is intuitive as AR antagonists block both testosterone and DHT whereas 5α-RIs only prevent conversion of testosterone into DHT. 

   [344]: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5023004/
   [345]: https://en.wikipedia.org/wiki/Benign_prostatic_hyperplasia
   [346]: https://en.wikipedia.org/wiki/Finasteride#Research
   [347]: http://doi.org/10.1111/andr.12881
   [348]: https://doi.org/10.1210/jc.2017-02052
   [349]: https://doi.org/10.1002/14651858.CD010334.pub2

There are three subtypes of 5α-reductase. Dutasteride inhibits all three subtypes of 5α-reductase whereas finasteride only inhibits two of the subtypes. As a result of this, dutasteride is a more complete 5α-RI than finasteride. Dutasteride decreases DHT levels in the blood by up to 98% while finasteride can only decrease them by around 65 to 70%. As nearly all circulating DHT originates from peripheral tissues, these decreases indicate parallel decreases in tissue DHT production (Horton, 1992). In accordance with these findings, dutasteride has been found to be more effective than finasteride in the treatment of scalp hair loss in men ([Zhou et al., 2018][350]; [Dhurat et al., 2020][351]; [Wiki][352]). For these reasons, although both finasteride and dutasteride are effective 5α-RIs, dutasteride may be the preferable choice if a 5α-RI is used (Zhou et al., 2018; Dhurat et al., 2020). 

   [350]: https://doi.org/10.2147/CIA.S192435
   [351]: https://doi.org/10.1111/dth.13379
   [352]: https://en.wikipedia.org/wiki/Dutasteride#Scalp_hair_loss

A potentially undesirable effect of 5α-RIs in transfeminine people is that they may increase testosterone levels to a certain degree in those whose testosterone production isn’t fully suppressed (Leinung et al., 2018; [Aly W., 2019][353]; [Traish et al., 2019][354]; Irwig, 2020). It appears that DHT adds significantly to negative feedback on gonadotropin secretion in the pituitary gland in people with testes who have low testosterone levels relative to the normal male range (Traish et al., 2019). The therapeutic implications of this for transfeminine people, if any, are uncertain. 

   [353]: https://transfemscience.org/articles/oral-e2-leinung-2018/
   [354]: https://doi.org/10.1016/j.sxmr.2018.06.002

Another potentially undesirable action of 5α-RIs is that they inhibit not only the production of DHT but also of certain [neurosteroids][355]. Neurosteroids are steroids that act on the [nervous system][356]—most notably the brain. Examples of neurosteroids that 5α-RIs inhibit the synthesis of include [allopregnanolone][357], which is formed from progesterone, and [3α-androstanediol][358], which is derived from testosterone and DHT. Research suggests that these neurosteroids have significant biological modulatory roles in mood, anxiety, stress, and other cognitive/emotional processes ([King, 2013][359]). Possibly in relation to this, 5α-RIs have been associated with a small risk of depression ([Welk et al., 2018][360]; [Deng et al., 2020][361]; [Dyson, Cantrell, & Lund, 2020][362]; [Nguyen et al., 2020][363]; [Wiki][364]). Claims of other, more significant and persistent side effects with 5α-RIs exist ([Traish, 2020][365]). However, they are based on low-quality reports and are controversial ([Fertig et al., 2016][366]; [Rezende, Dias, & Trüeb, 2018][367]). 

   [355]: https://en.wikipedia.org/wiki/Neurosteroid
   [356]: https://en.wikipedia.org/wiki/Nervous_system
   [357]: https://en.wikipedia.org/wiki/Allopregnanolone
   [358]: https://en.wikipedia.org/wiki/3%CE%B1-Androstanediol
   [359]: https://doi.org/10.1007/978-1-4614-5559-2_1
   [360]: https://doi.org/10.1001/jamainternmed.2017.0089
   [361]: https://doi.org/10.22037/uj.v16i7.5866
   [362]: https://doi.org/10.1097/JU.0000000000001079
   [363]: http://doi.org/10.1001/jamadermatol.2020.3385
   [364]: https://en.wikipedia.org/wiki/5%CE%B1-Reductase_inhibitor#Emotional_changes
   [365]: https://doi.org/10.1016/j.fertnstert.2019.11.030
   [366]: https://doi.org/10.1159/000450617
   [367]: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6369643/

Clinical [dose-ranging studies][368] have found that lower doses of finasteride and dutasteride than are typically used still provide substantial or near-maximal 5α-reductase inhibition ([Gormley et al., 1990][369]; [Vermeulen et al., 1991][370]; [Sudduth & Koronkowski, 1993][371]; [Drake et al., 1999][372]; [Roberts et al., 1999][373]; [Clark et al., 2004][374]; [Frye, 2006][375]; [Olsen et al., 2006][376]; [Harcha et al., 2014][377]; [Kuhl & Wiegratz, 2017][378]). In one study with finasteride for instance, DHT levels decreased by 49.5% at 0.05 mg/day, 68.6% at 0.2 mg/day, 71.4% at 1 mg/day, and 72.2% at 5 mg/day (Drake et al., 1999). Parallel reductions in DHT levels were seen locally in the scalp (Drake et al., 1999). In a study with dutasteride, DHT levels were decreased by 52.9% at 0.05 mg/day, 94.7% at 0.5 mg/day, 97.7% at 2.5 mg/day, and 98.4% at 5 mg/day (Clark et al., 2004). Based on these findings, 5α-RIs can potentially be taken at lower doses to help reduce medication costs if needed. 

   [368]: https://en.wikipedia.org/wiki/Dose-ranging_study
   [369]: https://doi.org/10.1210/jcem-70-4-1136
   [370]: https://doi.org/10.1159/000471752
   [371]: https://doi.org/10.1002/j.1875-9114.1993.tb02739.x
   [372]: https://doi.org/10.1016/S0190-9622(99)80051-6
   [373]: https://doi.org/10.1016/S0190-9622(99)80052-8
   [374]: https://doi.org/10.1210/jc.2003-030330
   [375]: https://doi.org/10.2174/156802606776743101
   [376]: https://doi.org/10.1016/j.jaad.2006.05.007
   [377]: https://doi.org/10.1016/j.jaad.2013.10.049
   [378]: https://doi.org/10.1007/s10304-017-0126-2

5α-Reductase inhibitors are taken orally in the form of tablets and capsules. 

Table: Available forms and recommended doses of 5α-reductase inhibitors: 

| Medication | Route | Form | Dosage |
| --- | --- | --- | --- |
| [Dutasteride][379] | Oral | Capsules | 0.05–2.5 mg/day |
| [Finasteride][380] | Oral | Tablets | 0.05–5 mg/day |

   [379]: https://en.wikipedia.org/wiki/Dutasteride
   [380]: https://en.wikipedia.org/wiki/Finasteride

####  GnRH Agonists and Antagonists 

GnRH agonists and antagonists (GnRHa) work by blocking the effects of GnRH in the pituitary gland and thereby suppressing LH and FSH secretion. Due to a physiological quirk, they have the same effects in this part of the body. This is because GnRH is normally secreted in pulses, and when the GnRH receptor is activated continuously, as with GnRH agonists, the GnRH receptor in the pituitary gland is desensitized to the point of becoming inactive. Consequently, both GnRH agonists and GnRH antagonists abolish gonadal sex hormone production. GnRHa are like a reversible gonadectomy, and for this reason, are also referred to as “medical castration”. Provided that an estrogen is taken in combination to prevent [sex hormone deficiency][381], GnRHa have essentially no side effects or risks. For these reasons, GnRHa are the ideal antiandrogens for use in transfeminine people. 

   [381]: https://en.wikipedia.org/wiki/Hypogonadism

GnRHa are widely used to suppess puberty in adolescent transgender individuals. Unfortunately however, they are very expensive (e.g., ~US$10,000 per year) and medical insurance does not usually cover them for adult transgender people. Consequently, GnRHa are not commonly used in adult transfeminine people at this time. An exception is in the United Kingdom, where GnRH agonists are covered for all adult transgender people by the [National Health Service][382] (NHS). Another exception is [buserelin][383] (Suprefact), which has become available very inexpensively in its nasal spray form from certain Eastern European online pharmacies in recent years ([Aly W., 2018][384]). 

   [382]: https://en.wikipedia.org/wiki/National_Health_Service
   [383]: https://en.wikipedia.org/wiki/Buserelin
   [384]: https://transfemscience.org/articles/buserelin-inexpensive/

GnRH agonists cause a brief flare in testosterone levels at the start of therapy ([Wiki][385]). Testosterone levels increase by up to about 1.5- to 2-fold for about 1 week and then decrease thereafter ([Wiki][385]). Castrate levels are reached within 2 to 4 weeks ([Wiki][385]). In contrast, because GnRH antagonists work by blocking the GnRH receptor without initially activating it, there is no testosterone flare with these agents and testosterone levels decrease immediately ([Wiki][385]). Antigonadotropins, for instance estrogens and progestogens, and potent androgen receptor antagonists like bicalutamide, can be used to prevent or blunt the effects of the testosterone flare at the initiation of GnRH agonist therapy if desired ([Wiki][385]). 

   [385]: https://en.wikipedia.org/wiki/Transgender_hormone_therapy_(male-to-female)#GnRH_modulators

GnRH agonists must be injected subcutaneously or intramuscularly once per day or once every one to six months (depending on the formulation). Alternatively, they can be [surgically implanted][386] once a year or used as a [nasal spray][387] two to three times per day. 

   [386]: https://en.wikipedia.org/wiki/Subcutaneous_implant
   [387]: https://en.wikipedia.org/wiki/Nasal_spray

Table: Available forms and recommended doses of GnRH agonists: 

| Medication | Brand name | Route | Form | Dosage |
| --- | --- | --- | --- | --- |
| [Buserelin][388] | Suprefact, others | SC injection | Solution | 200 μg/day<sup>a</sup> |
| | | | Implant | 6.3 mg/2 months |
| | | | | 9.45 mg/3 months |
| | Intranasal | Nasal spray | 400 µg 3x/day<sup>b,c</sup> |
| [Goserelin][389] | Zoladex | SC injection | Implant | 3.6 mg/month |
| | | | | 10.8 mg/3 months |
| [Histrelin][390] | Supprelin LA, Vantas | SC implant | Implant | 50 mg/year |
| [Leuprorelin][391] | Lupron, others | IM injection | Solution | 1 mg/day |
| | Eligard, Lupron Depot, others | IM/SC injection | Suspension | 3.75–7.5 mg/month |
| | | | | 11.25–22.5 mg/3 months |
| | | | | 30 mg/4 months |
| | | | | 45 mg/6 months |
| | Viadur | SC implant | Implant | 65 mg/year |
| [Nafarelin][392] | Synarel | Intranasal | Nasal spray | 400–600 μg 2–3x/day |
| [Triptorelin][393] | Decapeptyl, Trelstar Depot/LA | IM injection | Suspension | 3.75 mg/month |
| | | | | 11.25 mg/3 months |

   [388]: https://en.wikipedia.org/wiki/Buserelin
   [389]: https://en.wikipedia.org/wiki/Goserelin
   [390]: https://en.wikipedia.org/wiki/Histrelin
   [391]: https://en.wikipedia.org/wiki/Leuprorelin
   [392]: https://en.wikipedia.org/wiki/Nafarelin
   [393]: https://en.wikipedia.org/wiki/Triptorelin

<sup>a</sup> 500 μg 3x/day for the first week then 200 μg/day. <sup>b</sup> 800 μg 3x/day for the first week then 400 μg 3x/day. <sup>c</sup> 500 μg 2x/day can be used instead of 400 μg 3x/day but is less effective (70% decrease in testosterone levels (to ~180 ng/dL) instead of 90% decrease in testosterone levels (to ~50 ng/dL) per available studies of buserelin for prostate cancer) ([Aly W., 2018][394]; [Wiki][395]).

   [394]: https://transfemscience.org/articles/buserelin-inexpensive/
   [395]: https://en.wikipedia.org/wiki/Buserelin#Pharmacodynamics

The first GnRH antagonists were developed for use by once-monthly intramuscular or subcutaneous injection. More recently, orally administered GnRH antagonists such as elagolix and [relugolix][396] have been introduced for medical use ([Aly W., 2018][397]; [Aly W., 2019][398]). They are taken once or twice daily. 

   [396]: https://en.wikipedia.org/wiki/Relugolix
   [397]: https://transfemscience.org/articles/elagolix-approval/
   [398]: https://transfemscience.org/articles/relugolix-approval/

Table: Available forms and recommended doses of GnRH antagonists: 

| Medication | Brand name | Route | Form | Dosage |
| --- | --- | --- | --- | --- |
| [Abarelix][399] | Plenaxis | IM injection | Suspension | 113 mg/month |
| [Degarelix][400] | Firmagon | SC injection | Solution | 80 mg/month<sup>a</sup> |
| [Elagolix][401] | Orilissa | Oral | Tablets | 150–200 mg 1–2x/day<sup>b</sup> |
| [Relugolix][402] | Relumina | Oral | Tablets | 40 mg/day |

   [399]: https://en.wikipedia.org/wiki/Abarelix
   [400]: https://en.wikipedia.org/wiki/Degarelix
   [401]: https://en.wikipedia.org/wiki/Elagolix
   [402]: https://en.wikipedia.org/wiki/Relugolix

<sup>a</sup> First month is 240 mg then 80 mg per month thereafter. <sup>b</sup> 150 mg 1x/day is less effective than 200 mg 2x/day (which provides full gonadal sex-hormone suppression in cisgender women) ([Wiki][403]).

   [403]: https://en.wikipedia.org/wiki/Elagolix#Pharmacodynamics

####  Additional Notes 

There is relatively little variability between individuals with antiandrogens. 

After removal of the gonads, antiandrogens can be discontinued. If unwanted androgen-dependent symptoms occur, such as acne, seborrhea, or scalp hair loss, then a lower dose of an AR antagonist, such as 100 to 200 mg/day spironolactone or 12.5 to 25 mg/day bicalutamide, can be continued. 

###  Androgens and Anabolic Steroids 

In addition to estrogens, progestogens, and antiandrogens, [androgens/anabolic steroids][404] (AAS) are sometimes added to transfeminine hormone therapy. This is when testosterone levels are low (e.g., below the female average of 30 ng/dL) and androgen replacement is desired. It has been proposed that adequate levels of testosterone may provide benefits such as increased sexual desire, improved mood and energy, positive effects on skin health and [cellulite][405] ([Avram, 2004][406]), and increased muscle size and strength ([Huang & Basaria, 2017][407]). However, there is insufficient clinical evidence to support such benefits at present ([Wiki][408]). In any case, possible options for androgen therapy include [testosterone][409], [dehydroepiandrosterone][410] (DHEA; prasterone), and [nandrolone decanoate][411] (ND) ([Aly W., 2020][412]). 

   [404]: https://en.wikipedia.org/wiki/Anabolic_steroid
   [405]: https://en.wikipedia.org/wiki/Cellulite
   [406]: https://doi.org/10.1080/14764170410003057
   [407]: https://doi.org/10.1007/978-3-319-42451-4_10
   [408]: https://en.wikipedia.org/wiki/Testosterone_(medication)#Women
   [409]: https://en.wikipedia.org/wiki/Testosterone_(medication)
   [410]: https://en.wikipedia.org/wiki/Prasterone
   [411]: https://en.wikipedia.org/wiki/Nandrolone_decanoate
   [412]: https://transfemscience.org/articles/nandrolone/

##  Monitoring of Therapy 

Transfeminine people on hormone therapy should undergo regular laboratory [monitoring][413] in the form of [blood work][414]. Total estradiol levels and total testosterone levels should be measured to assess the effectiveness of therapy and determine whether medication adjustments may be necessary. Levels of free testosterone, free estradiol, [estrone][415] (E1), dihydrotestosterone (DHT), luteinizing hormone (LH), follicle-stimulating hormone (FSH), and [sex hormone-binding globulin][416] (SHBG) can be also be measured to provide further information although they’re not absolutely necessary. If progesterone is used, progesterone levels can be measured. However, in the specific case of oral progesterone, progesterone levels should be measured with a [mass spectrometry][417]-based test and not with an [immunoassay][418] ([Aly W., 2018][419]; [Wiki][420]). Conversely, either type of assay may be used with non-oral progesterone. 

   [413]: https://en.wikipedia.org/wiki/Monitoring_(medicine)
   [414]: https://en.wikipedia.org/wiki/Blood_test
   [415]: https://en.wikipedia.org/wiki/Estrone
   [416]: https://en.wikipedia.org/wiki/Sex_hormone-binding_globulin
   [417]: https://en.wikipedia.org/wiki/Mass_spectrometry
   [418]: http://en.wikipedia.org/wiki/Immunoassay
   [419]: https://transfemscience.org/articles/oral-p4-low-levels/
   [420]: https://en.wikipedia.org/wiki/Pharmacokinetics_of_progesterone#Oral_progesterone

[Liver function tests][421] (LFTs) should be regularly performed to monitor for liver toxicity in transfeminine people taking bicalutamide or high doses of CPA (≥20 mg/day). In those with relevant risk factors for hyperkalemia (e.g., older age) who are taking spironolactone, potassium levels should be monitored. In transfeminine people taking high doses of estrogens and/or progestogens (particularly CPA), [prolactin][422] levels should be regularly measured to monitor for the development of prolactinoma. If these tests come back abnormal, depending on the situation and its severity, doses should be reduced or specific medications should be discontinued entirely or replaced with alternatives where applicable. 

   [421]: https://en.wikipedia.org/wiki/Liver_function_tests
   [422]: http://en.wikipedia.org/wiki/Prolactin
